### PR TITLE
feat: upgrade code of conduct policy #

### PR DESCRIPTION
**Pull request by Aju100**
Issue: https://github.com/ortelius/ortelius/issues/445
Changes: Update the policy via https://www.contributor-covenant.org/version/2/1/code_of_conduct/

### CODE REVIEW

**Comment by markjacksonfishing** [comment]
Is there more context for these changes to the CoC?

**Review by markjacksonfishing — CHANGES_REQUESTED** [review]
/hold

**Comment by Aju100** [comment]
@markyjackson-taulia Not sure more context but as far as I know from the issue, it has been assigned to update CoC for the lastest one.

**Comment by markjacksonfishing** [comment]
> @markyjackson-taulia Not sure more context but as far as I know from the issue, it has been assigned to update CoC for the lastest one.

What is "for the latest one"? 
Please help me understand The Who, what, why, and where.
/hold

**Comment by Aju100** [comment]
Oh Seems like I didn't fully understand issue https://github.com/ortelius/ortelius/issues/445. I am closing this PR. thanks @markyjackson-taulia

**Pull request closed without merging**
