### PR TITLE
Use Fedora 34 for base images

### PR DESCRIPTION
**Pull request by sbtaylor15**
Change to 34 and update package deps

### CODE REVIEW

**Review by markjacksonfishing — COMMENTED** [review]
I know this may not be the most popular thing to say but this pr really should have been broken up in to more digestible chunks.
A 20k line pr change on an oss project, with nothing to go on besides the actual line changes is just unfair to any reviewer. How does this project fix that?

**Comment by sbtaylor15** [comment]
> I know this may not be the most popular thing to say but this pr really should have been broken up in to more digestible chunks. A 20k line pr change on an oss project, with nothing to go on besides the actual line changes is just unfair to any reviewer. How does this project fix that?

I need to redo the commits in the PR.  Looks like the merge didn't work correctly.

**Comment by sbtaylor15** [comment]
@markyjackson-taulia  ok, figured it out.  The PR was created against main and not svc_cat branch.  Changed the "to" branch and looking much better.

**Review by markjacksonfishing — APPROVED** [review]
ah! Ok, that makes total sense. Haha, I was like 20k+ lines, this is going to take awhile hehe.
have an awesome weekend!

**Pull request merged**
