### PR TITLE
add briahi to contributors

### PR DESCRIPTION
**Pull request by briahi**

### CODE REVIEW

**Review by markjacksonfishing — CHANGES_REQUESTED** [review]
Please kindly sign the EasyCLA

**Comment by briahi** [comment]
could anyone help ? I already signed the easy cla

**Review by markjacksonfishing — APPROVED** [review]
Kindly sign the easycla

**Comment by sbtaylor15** [comment]
> could anyone help ? I already signed the easy cla

Looks like there is an issue with the CLA hook.  ` is missing the User's ID`.    Skipping CLA for now.

**Pull request merged**
