### PR TITLE
Issue #377 - create github actions workflow for helm-chart-releaser

### PR DESCRIPTION
**Pull request by benhpoh**
Add a github action to use helm-chart-releaser to automate packaging and indexing of helm charts to ortelius' Github pages.

This will allow the helm charts to be hosted on Artifact Hub.

### CODE REVIEW

**Review by markjacksonfishing — APPROVED** [review]

**Review by bradmccoydev — APPROVED** [review]
LGTM. Note: relates to issue #377 and is linked to PR: 397 also no changes are required for secrets.GITHUB_TOKEN

**Comment by sbtaylor15** [comment]
@benhpoh @bradmccoydev how will charts coming from outside of the repo be handled.  Will we need an action on those repos as well to push those charts to the Ortelius Pages?

**Comment by benhpoh** [comment]
@sbtaylor15 this same github action will be applied to each of the ortelius/* repos with charts, which in turn will then create and self host their respective chart releases. 

This way, we can avoid having any cross repo dependencies.

**Comment by sbtaylor15** [comment]
@benhpoh thats what I figured.  I created issue #401 to track this.

**Pull request merged**
